### ISSUE TITLE
class inheritance error

### ISSUE THREAD

**Issue by iancballard** [mwaskom/sticks_experiment#1]
Hi Michael,

I know this isn't code you maintain so feel free to ignore me, but I'm stuck on a bug (I'm presuming a version issue). Do you have any ideas as to what might be going wrong? Or, what version of psychopy were you using at the time?

python sticks.py instruct
Traceback (most recent call last):
  File "sticks.py", line 961, in <module>
    class PolygonCue(visual.Polygon):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by mwaskom** [comment]
I think I’ve seen this once before but don’t remember all the details. I don’t think it’s a version issue. Something is telling me that importing the class you’re inheriting from directly might solve it.

**Comment by mwaskom** [comment]
Ah yes, see https://github.com/psychopy/psychopy/issues/1159

**Comment by mwaskom** [comment]
So specifically you'll need to do

```python
from psychopy.visual.polygon import Polygon

class PolygonDerivative(Polygon):
    ...

```
